language: python
cache: pip
install:
- pip install -r requirements.txt
script: mkdocs build --clean
deploy:
  provider: pages
  local-dir: site/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
notifications:
  email: false