language: python
cache: pip
install:
- pip install -r requirements.txt
script: mkdocs build --clean
deploy:
  provider: pages
  local-dir: site/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: ZGakr+ZCLaKlZGCZLGP13c6060T6Sw8Kh17GcNaTgCpFPbPQqWBZojcbPBanz59z9eEHYeh4bsMbTHCs3wkfX5NZOQD/HoG9E/4DcbTSOSTdOyyxLU66+qIDmzb9B1BWFiB+FZRqQcST9zifmXUYo3e1CTdBzhHzGsRO18U1tXBSPabRiVtROkwMwuX7RwW2KCpasVc3k7YvJG96ChrfTl/3ZClN13/2nnO2UcDot8+yz2aqgJB6YA0G5QihQvE/0S1FCxePHrtoOlzMSY53txiS28QQusE9Q/O5C7EJWddx14wiUgqqLfwPAAnV/hnTywjlQHT1Vjfflj1PxSN+t1M+r4MLTGjiUXZA78U0R1ZZ5/RzzynLe/Np0pAKHqrNveUQTzPXgZ02HCtqlvs5nPdTYeHhm7tTMR72dr2AsQ37ZRRIqTze5mX72qsmNrk4futC/tjn39mM/UMuu1sLsxwz1zuxRL1Qqg9jIpMyxwMHBmjXZfqnLLUWTjXLVAOVmwlJD4pt5Qj67p+COoXlJUx3wCxD4GbcF8ucom//gK2o1b2bOyxaKUS0GM6raLG2d4ZHVxloYGicYF4ilMjTvtjM/UhPlOrgWdp3McNM4BWdSTpGevUvyEYLdau//GgEKi9nfbo/TMGl/c9csmh90Oa2FlnJxSmzeSNFVW6ye3g=
env:
  global:
    secure: UGEOwWhU7/+g+7m1066vCe8M2qEjKjbOJEoYPbVE0gLhVMdoW7Ydg2ePMFk2nO1QALCOQOfAYFnUiIoUg3WMTVlGKh7OEkOZIyx6YBgHrGSypvB8C89K6AAvg4FQWoM/0N5T7vrd8yUXxleHCbRuolrDBmNwf2E3klDy2GK4wqDE44wOqAjeDnh6D4Y+OoFppsevdMButp94/C72SkASSZS2guR5Zlt9bCQYyldqQpfGQMD+5vwoNZXwz1x71eJfR7mhnfF4qr+uAx4XpOP4cmu8hLjGsp8A7PvR5yhA45naYjL8hm9MV5RqQZiCdGp3P/MgnmayS28u716BfjmDyZN8YwHsEthlAqEJnGdgy0oPX9mot2gbKeka7KEiOrVUGScW8fxpDK3ebeHso9lbK2AIcgm52O/jTR5ul0fxZmkq6LUc8WF7eerQ3SACckmuDeYWfaJVBpawjb2L83XVF4ucEMdWFdkX5IYgZvpHce4hgFAkvdmao/Zio9N/jsfWRlQxe3PEEegQn+/LYof8n5HREghSW9rEWMeK3kwtxAku6mXYMcRdj5JHW5ZjDjfUcs21nyGCxVwcVKgtjY/uIr1JC6iLpOE5Jx9mfpylVqVk8hu0QBreylwjO9H2JZ2HrljaQw/bIOw8p90cm8ix0zwkPc190JMyc+jdQ1/5mfM=
